In [1]:
from joke_agent import Joke
from funfact_agent import FunFact
from puzzle_agent import Puzzle

In [5]:
user_id = "user-1"

In [6]:
await Joke(user_id=user_id)

I bought a ceiling fan. Complete waste of money—he just stands there applauding the ceiling.

In [7]:
await FunFact(user_id=user_id)

Octopuses can taste with their arms! Their suckers contain specialized sensory cells that help them chemically “sample” whatever they touch.

In [8]:
await Puzzle(user_id=user_id)

One-word puzzle game (type quit to leave).

Puzzle host: I’m a punctuation mark that can show ownership or take the place of missing letters. What am I?

Take a guess, ask for a hint, or ask for the answer!
Thanks for playing!

In [14]:
# Run again with the same user ID to keep the conversation history.
await Joke(user_id=user_id)
await FunFact(user_id=user_id)
await Puzzle(user_id=user_id)

I bought a ceiling fan yesterday. Complete waste of money—he just stands there yelling, “Go, ceiling!”
Octopuses can taste with their suckers! Specialized sensory cells help them detect chemicals on surfaces, so touching something can also help them decide whether it’s food.
One-word puzzle game (type quit to leave).

Puzzle host: I have keys but open no locks, a space but no room, and an Enter but no doorway. What am I?

Take a guess, ask for a hint, or ask for the answer!
Thanks for playing!

In [2]:
from handle_database import display_db_contents, empty_history,print_db_tables,export_history_json

In [13]:
# empty_history(session_id="user-1", task="puzzles")
# empty_history(session_id="user-1", task="jokes")
# empty_history(session_id="user-1", task="facts")

In [10]:
display_db_contents(session_id="user-1", task="jokes")

History for user-1:jokes (3 messages):

,id,session_id,message_data,created_at
0,1,user-1:jokes,"{""content"": ""Tell me a joke."", ""role"": ""user""}",2026-10-02 15:32:46
1,2,user-1:jokes,"{""id"": ""rs_03e62119ca3a2411006abfcea182cc87d29...",2026-10-02 15:32:50
2,3,user-1:jokes,"{""id"": ""msg_03e62119ca3a2411006abfcea1b92c87d2...",2026-10-02 15:32:50

,id,session_id,message_data,created_at
0,1,user-1:jokes,"{""content"": ""Tell me a joke."", ""role"": ""user""}",2026-10-02 15:32:46
1,2,user-1:jokes,"{""id"": ""rs_03e62119ca3a2411006abfcea182cc87d29...",2026-10-02 15:32:50
2,3,user-1:jokes,"{""id"": ""msg_03e62119ca3a2411006abfcea1b92c87d2...",2026-10-02 15:32:50

In [11]:
display_db_contents(session_id="user-1", task="puzzles")

History for user-1:puzzles (3 messages):

,id,session_id,message_data,created_at
0,6,user-1:puzzles,"{""content"": ""Start a new one-word puzzle."", ""r...",2026-10-02 15:32:53
1,7,user-1:puzzles,"{""id"": ""rs_014643ba85c2cbba006abfcea98a5887d29...",2026-10-02 15:33:01
2,8,user-1:puzzles,"{""id"": ""msg_014643ba85c2cbba006abfceac8eac87d2...",2026-10-02 15:33:01

,id,session_id,message_data,created_at
0,6,user-1:puzzles,"{""content"": ""Start a new one-word puzzle."", ""r...",2026-10-02 15:32:53
1,7,user-1:puzzles,"{""id"": ""rs_014643ba85c2cbba006abfcea98a5887d29...",2026-10-02 15:33:01
2,8,user-1:puzzles,"{""id"": ""msg_014643ba85c2cbba006abfceac8eac87d2...",2026-10-02 15:33:01

In [12]:
display_db_contents(session_id="user-1", task="facts")

History for user-1:facts (2 messages):

,id,session_id,message_data,created_at
0,4,user-1:facts,"{""content"": ""Tell me a fun fact."", ""role"": ""us...",2026-10-02 15:32:50
1,5,user-1:facts,"{""id"": ""msg_0975bd762c8ffd35006abfcea46da487d2...",2026-10-02 15:32:53

,id,session_id,message_data,created_at
0,4,user-1:facts,"{""content"": ""Tell me a fun fact."", ""role"": ""us...",2026-10-02 15:32:50
1,5,user-1:facts,"{""id"": ""msg_0975bd762c8ffd35006abfcea46da487d2...",2026-10-02 15:32:53

In [4]:
history_json = export_history_json("user-1", "puzzles")
print(history_json)

{
  "session_id": "user-1:puzzles",
  "task": "puzzles",
  "messages": [
    {
      "id": 6,
      "created_at": "2026-10-02 15:32:53",
      "message_data": {
        "content": "Start a new one-word puzzle.",
        "role": "user"
      }
    },
    {
      "id": 7,
      "created_at": "2026-10-02 15:33:01",
      "message_data": {
        "id": "rs_014643ba85c2cbba006abfcea98a5887d296aaa10d5552f932",
        "summary": [],
        "type": "reasoning",
        "content": [],
        "encrypted_content": "gAAAAABqv86t62q0PXD-yv0bG3_UfCmVxWi1ORz0I4XPoLWGXlWP2iHZcgpYz5PBkcJoS1d6kllS-M4p_QqKJPKthrfgDX6eR60j3VRVVJnecWiPBjVPXTvCOAggIvo6QMxE_HVtBuKElW8ggp38Iwm0wqczx0Tb3gyui3HcYXH_onbj6DaRlc5TI1cYuvWcSF2Ucr6TyC6-O5qUlcWeWx_yKyfPI4aCaAe0-YAQHPTs9iy7wg_luxWq1NHapjmW7MYbXcDFA9ob3nzGtJNzoWIy4ozuretc66SsYtpREjjFytY8OhTZximb6-Ccq5-MCDm7H84a-4anerfRK01cKZsbuyOzt65JdYZmHRUB5E9E3pGXgwwFfeQwdkoOK4TJGWUvlps6bploqWQ3yZ5E7-GOalgfKR_VqiwlDf_FpKu8xnO5yteyokfYOpqxIrWNnITA5NU7Wn2LAdgTdS23waaczgpYNUGxrQJAKY5CVZMd2sdxuYg6eCY9ePpfbhx9OMsuwn_iZf99XDKO6HNATMSZRNQZQRsiLTOscGC3MKoyBPYpBQSv58Je6QeE7jSr2xeJpsuwhNUTlHjBcjyQ147QDz7f3CKjhbbqrQu1EM-hbechoWEsydsWu98bovR7Wc8Z3i7f75sitByrYExmHZjH2ZUy6qvIr1lyf61v9QycfqgUL2wSbtH3jq2eyoAQ0F2cBChS4uXKVguIEFApEEHOJ52z5JkXgiiUWLfsV9Lg9eBtAoI-s2sUHaFymQlfYWni-zkEQnpo2sokPNU7epKAsrQ_7Wd2VuUtgzKPAba1Qk8QZtFnDEYOKifQcRic3QxM7mJWfc9CK5rpOgU6q3861zqhx4eXVXI25R-sqfgLy0EJXtsCDrYnsq16tDmveGYrrJLkMvIy9MHfokVS-hXKYG6qFxfQP09oAJf4XTxh8n9NruMvSeNyF3ZqKGgVzoiJm_RvYVybobdRRFT6wNtU1S4VWtORNgpY-XGg9pzDB8SCZCaj7a5wCIcXQWy0ab51LWM8pMNUM5WhPr0-PqiCTT4L97HbG3AWR6LN3Z2wi2rZjH6hD91NJezpvwDEao5uuB2QB3MjiEEAj93PmB7eEJA1P77E0xFZrUpjA7bV8w80q0-4b8GInkWo_eLUk1Nz7alRxyf9dhkoUYNpYMLW0EvLUOVK1XI7FYy4lFjxhtBqstGmgvWXU1trX_hiuVgjary-MqIoLUutyTxgOesBENrl7d87kRm4YRRm_k_GMm9k64UpzG4n2beWvDarC_k7_60HKGDLaSdtK1QZxVpk9hWkqX8hHisrzkytU5-osIvgUIjoUt0o_m5D9VXc07ZCtI1jt2kZdnC6PmXInmdaSKpBgBz9reXWDrDiCvDBw7q-fZTSBz7Ebsj6-mWT26jiokoox-kruHafp_fEcO1ooj_g095Qbi60qO_-JUlnK8T3wwYGvghDxmt7vN5LXl9iFb7B4-6ZOAFYaC7YJoDWUgDO1ChRnbBpuuhQXq9sbs_JLzLukBjZRlXlMy_onCdL3w01LDYg2SBCs8cgRzYaxIeHLtpqNWZtXES7TH8MBSIu00cFaKkYoEOfbLMfHUnjlhU_g5wrE8-kZSpdQUO49JVYS_r_O21eX5ZzgzlTVcF4MiKXcNaV1vwdXk-WOw78CVkq9iJv"
      }
    },
    {
      "id": 8,
      "created_at": "2026-10-02 15:33:01",
      "message_data": {
        "id": "msg_014643ba85c2cbba006abfceac8eac87d2a8102817477aa01d",
        "content": [
          {
            "annotations": [],
            "text": "{\"message\":\"I’m a punctuation mark that can show ownership or take the place of missing letters. What am I?\\n\\nTake a guess, ask for a hint, or ask for the answer!\",\"status\":\"playing\"}",
            "type": "output_text",
            "logprobs": []
          }
        ],
        "role": "assistant",
        "status": "completed",
        "type": "message",
        "phase": "final_answer"
      }
    }
  ]
}

In [15]:
tables = print_db_tables()

Table: agent_sessions (3 rows)
    session_id          created_at          updated_at
  user-1:facts 2026-10-02 15:32:50 2026-10-02 15:32:53
  user-1:jokes 2026-10-02 15:32:46 2026-10-02 15:32:50
user-1:puzzles 2026-10-02 15:32:53 2026-10-02 15:33:01

Table: agent_messages (8 rows)
 id     session_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message_data          created_at
  1   user-1:jokes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {"content": "Tell me a joke.", "role": "user"} 2026-10-02 15:32:46
  2   user-1:jokes                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {"id": "rs_03e62119ca3a2411006abfcea182cc87d2902fcb8d88dba47a", "summary": [], "type": "reasoning", "content": [], "encrypted_content": "gAAAAABqv86i4w7CMcPLi69kzCVkLfpdMU9AURkgGd80Niftiy2DA1-6xYm67YohdvlQYRKTgY7lf8ZH90jAwD0nex_ArxXWeeQPNcIS_1l0zFfjS35QKDgBJeQ8qw8-lSViM4B5kDiGmm_w7vo-LaVp3M0nDMG55-iz2T1hMPfnQkp64TV5iczGISjptT01DTMz6mFTWFBUa7fMZyPQ7hDB1CFD4oFR6YiokcEQC-D8_-3G1U2x865qmo731QiOqvRWXHAxGOP4j_SBAhRF4RUn9GP_jOlHS9eYctFPsFNwB0ZyfixbfENQu_s4iUNEsZ_89YIRF9Qyf8y_ifoJwFGloNhqjlMYH0l6q3YPG_dTERjW5HyES90CJh98iAVQo-J8cvMQoIHGVYccCOHupcvqUlAJ8BLhH_NsrdIS0SWsxkOlBO_unFVlL0pFnw7ceOKMixG5rkwp5lH59PtpBkf2qNMkI9SVM0SaKDiWRIgSrkVwW8PTSo9GKr3e2DHSFPq4Vd8YPuapWbsEzRlwKQz5Zs06l5RcgiGq10CEQUSMJp-XqDFh46B8FRnvfH6_ye2tLo-451a6AYRjpVnywXPjg0Flsn3rvsXDF2Xa4xoBR8sk8FsCFfYfldIyYBDryFsC70RdR3YbUEbV8SlRp4lt_psLkIGvp_HB8aqOcMiOVhi9369i6uk-zy47n9F6Ehd3kFH70zLDuD00nKkoXyoyj1QDnJZ_51PmPcyVZood7pf9zchVPE7OPW5m0gu2X8cuYDzJtmC-bcgY98tFzipwy2w6F2pdCAV9EHVWhpeMRUyiQcbVwoFNExOjPz5KFI0O-rdg9-MfYmDtvmCWWQNZhebY0WeLOk-iURxFxFb-UO6GhCHG4I6RYVk91elZ5rCHrbc-3jTi1omUuAQhtcrHKFsxPUxox-M9NuuqB3EeQwslLGwULorNxoxIUIsjYZgZTXAO4COg-vaSUM4svp0b1H4PNMizO6mLxkmfEGebTqgGSfj4FM5DJxattn65uSddVMlZn4eV5JHPU7M_9Z9Y0M8Ul0A9yIABeNH-06MFLTHYEGHtAIet0Sk7XZsgHRghMQt9IEOf7xjafPgluy1UaDH8p5mQSnUpr8Ign67J-qq2OQjdJZmnVCqUxO-bsn9kOMZCDAJyhPw6AkDDoGUR-EyxkyS0y2jvKNLMTFM-Iw7uzoiJzQDsSgesGkTN94RFfr8iGHQ7"} 2026-10-02 15:32:50
  3   user-1:jokes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {"id": "msg_03e62119ca3a2411006abfcea1b92c87d2874ab30cf8239242", "content": [{"annotations": [], "text": "I bought a ceiling fan. Complete waste of money\u2014he just stands there applauding the ceiling.", "type": "output_text", "logprobs": []}], "role": "assistant", "status": "completed", "type": "message", "phase": "final_answer"} 2026-10-02 15:32:50
  4   user-1:facts                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {"content": "Tell me a fun fact.", "role": "user"} 2026-10-02 15:32:50
  5   user-1:facts                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {"id": "msg_0975bd762c8ffd35006abfcea46da487d289ade8c5d5dc47a8", "content": [{"annotations": [], "text": "Octopuses can taste with their arms! Their suckers contain specialized sensory cells that help them chemically \u201csample\u201d whatever they touch.", "type": "output_text", "logprobs": []}], "role": "assistant", "status": "completed", "type": "message", "phase": "final_answer"} 2026-10-02 15:32:53
  6 user-1:puzzles                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {"content": "Start a new one-word puzzle.", "role": "user"} 2026-10-02 15:32:53
  7 user-1:puzzles {"id": "rs_014643ba85c2cbba006abfcea98a5887d296aaa10d5552f932", "summary": [], "type": "reasoning", "content": [], "encrypted_content": "gAAAAABqv86t62q0PXD-yv0bG3_UfCmVxWi1ORz0I4XPoLWGXlWP2iHZcgpYz5PBkcJoS1d6kllS-M4p_QqKJPKthrfgDX6eR60j3VRVVJnecWiPBjVPXTvCOAggIvo6QMxE_HVtBuKElW8ggp38Iwm0wqczx0Tb3gyui3HcYXH_onbj6DaRlc5TI1cYuvWcSF2Ucr6TyC6-O5qUlcWeWx_yKyfPI4aCaAe0-YAQHPTs9iy7wg_luxWq1NHapjmW7MYbXcDFA9ob3nzGtJNzoWIy4ozuretc66SsYtpREjjFytY8OhTZximb6-Ccq5-MCDm7H84a-4anerfRK01cKZsbuyOzt65JdYZmHRUB5E9E3pGXgwwFfeQwdkoOK4TJGWUvlps6bploqWQ3yZ5E7-GOalgfKR_VqiwlDf_FpKu8xnO5yteyokfYOpqxIrWNnITA5NU7Wn2LAdgTdS23waaczgpYNUGxrQJAKY5CVZMd2sdxuYg6eCY9ePpfbhx9OMsuwn_iZf99XDKO6HNATMSZRNQZQRsiLTOscGC3MKoyBPYpBQSv58Je6QeE7jSr2xeJpsuwhNUTlHjBcjyQ147QDz7f3CKjhbbqrQu1EM-hbechoWEsydsWu98bovR7Wc8Z3i7f75sitByrYExmHZjH2ZUy6qvIr1lyf61v9QycfqgUL2wSbtH3jq2eyoAQ0F2cBChS4uXKVguIEFApEEHOJ52z5JkXgiiUWLfsV9Lg9eBtAoI-s2sUHaFymQlfYWni-zkEQnpo2sokPNU7epKAsrQ_7Wd2VuUtgzKPAba1Qk8QZtFnDEYOKifQcRic3QxM7mJWfc9CK5rpOgU6q3861zqhx4eXVXI25R-sqfgLy0EJXtsCDrYnsq16tDmveGYrrJLkMvIy9MHfokVS-hXKYG6qFxfQP09oAJf4XTxh8n9NruMvSeNyF3ZqKGgVzoiJm_RvYVybobdRRFT6wNtU1S4VWtORNgpY-XGg9pzDB8SCZCaj7a5wCIcXQWy0ab51LWM8pMNUM5WhPr0-PqiCTT4L97HbG3AWR6LN3Z2wi2rZjH6hD91NJezpvwDEao5uuB2QB3MjiEEAj93PmB7eEJA1P77E0xFZrUpjA7bV8w80q0-4b8GInkWo_eLUk1Nz7alRxyf9dhkoUYNpYMLW0EvLUOVK1XI7FYy4lFjxhtBqstGmgvWXU1trX_hiuVgjary-MqIoLUutyTxgOesBENrl7d87kRm4YRRm_k_GMm9k64UpzG4n2beWvDarC_k7_60HKGDLaSdtK1QZxVpk9hWkqX8hHisrzkytU5-osIvgUIjoUt0o_m5D9VXc07ZCtI1jt2kZdnC6PmXInmdaSKpBgBz9reXWDrDiCvDBw7q-fZTSBz7Ebsj6-mWT26jiokoox-kruHafp_fEcO1ooj_g095Qbi60qO_-JUlnK8T3wwYGvghDxmt7vN5LXl9iFb7B4-6ZOAFYaC7YJoDWUgDO1ChRnbBpuuhQXq9sbs_JLzLukBjZRlXlMy_onCdL3w01LDYg2SBCs8cgRzYaxIeHLtpqNWZtXES7TH8MBSIu00cFaKkYoEOfbLMfHUnjlhU_g5wrE8-kZSpdQUO49JVYS_r_O21eX5ZzgzlTVcF4MiKXcNaV1vwdXk-WOw78CVkq9iJv"} 2026-10-02 15:33:01
  8 user-1:puzzles                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {"id": "msg_014643ba85c2cbba006abfceac8eac87d2a8102817477aa01d", "content": [{"annotations": [], "text": "{\"message\":\"I\u2019m a punctuation mark that can show ownership or take the place of missing letters. What am I?\\n\\nTake a guess, ask for a hint, or ask for the answer!\",\"status\":\"playing\"}", "type": "output_text", "logprobs": []}], "role": "assistant", "status": "completed", "type": "message", "phase": "final_answer"} 2026-10-02 15:33:01