In [1]:
from joke_agent import Joke
from funfact_agent import FunFact
from puzzle_agent import Puzzle

In [2]:
user_id = "user-1"

In [5]:
await Joke(user_id=user_id)

My dentist said I need a crown. I said, “Finally—someone recognizes my royal potential.”

In [8]:
await FunFact(user_id=user_id)

Octopuses have three hearts: two pump blood to the gills, while the third pumps it to the rest of the body.

In [9]:
await Puzzle(user_id=user_id)

One-word puzzle game (type quit to leave).

Puzzle host: I show roads, rivers, and mountains, but contain no actual land or water. What am I? Guess, ask for a hint, or ask for the answer.

Puzzle host: Correct! The answer is **map**: it represents roads, rivers, and mountains without containing the real things.

In [14]:
# Run again with the same user ID to keep the conversation history.
await Joke(user_id=user_id)
await FunFact(user_id=user_id)
await Puzzle(user_id=user_id)

I bought a ceiling fan yesterday. Complete waste of money—he just stands there yelling, “Go, ceiling!”
Octopuses can taste with their suckers! Specialized sensory cells help them detect chemicals on surfaces, so touching something can also help them decide whether it’s food.
One-word puzzle game (type quit to leave).

Puzzle host: I have keys but open no locks, a space but no room, and an Enter but no doorway. What am I?

Take a guess, ask for a hint, or ask for the answer!
Thanks for playing!

In [2]:
from handle_database import get_db_contents, empty_history,get_db_tables,get_history_json

In [13]:
# empty_history(session_id="user-1", task="puzzles")
# empty_history(session_id="user-1", task="jokes")
# empty_history(session_id="user-1", task="facts")

In [3]:
get_db_contents(session_id="user-1", task="jokes")

,id,session_id,message_data,created_at
0,7,user-1:jokes,"{""content"": ""Tell me a joke."", ""role"": ""user""}",2026-10-03 09:28:40
1,8,user-1:jokes,"{""id"": ""rs_09fe2fd1198667a0006ac0cac9930887d1a...",2026-10-03 09:28:42
2,9,user-1:jokes,"{""id"": ""msg_09fe2fd1198667a0006ac0caca15a487d1...",2026-10-03 09:28:42
3,10,user-1:jokes,"{""content"": ""Tell me a joke."", ""role"": ""user""}",2026-10-03 09:28:53
4,11,user-1:jokes,"{""id"": ""rs_09fe2fd1198667a0006ac0cad7140c87d1b...",2026-10-03 09:28:55
5,12,user-1:jokes,"{""id"": ""msg_09fe2fd1198667a0006ac0cad7364887d1...",2026-10-03 09:28:55
6,13,user-1:jokes,"{""content"": ""Tell me a joke."", ""role"": ""user""}",2026-10-03 09:29:10
7,14,user-1:jokes,"{""id"": ""rs_09fe2fd1198667a0006ac0cae7236c87d19...",2026-10-03 09:29:12
8,15,user-1:jokes,"{""id"": ""msg_09fe2fd1198667a0006ac0cae84b2487d1...",2026-10-03 09:29:12

In [4]:
get_db_contents(session_id="user-1", task="puzzles")

,id,session_id,message_data,created_at
0,1,user-1:puzzles,"{""content"": ""Start a new one-word puzzle."", ""r...",2026-10-03 09:26:38
1,2,user-1:puzzles,"{""id"": ""rs_01960a77135184a0006ac0ca50fe2087d1a...",2026-10-03 09:26:42
2,3,user-1:puzzles,"{""id"": ""msg_01960a77135184a0006ac0ca5213fc87d1...",2026-10-03 09:26:42
3,4,user-1:puzzles,"{""content"": ""candle"", ""role"": ""user""}",2026-10-03 09:27:15
4,5,user-1:puzzles,"{""id"": ""rs_01960a77135184a0006ac0ca74e70087d19...",2026-10-03 09:27:17
5,6,user-1:puzzles,"{""id"": ""msg_01960a77135184a0006ac0ca75194887d1...",2026-10-03 09:27:17
6,25,user-1:puzzles,"{""content"": ""Start a new one-word puzzle."", ""r...",2026-10-03 09:30:43
7,26,user-1:puzzles,"{""id"": ""rs_01960a77135184a0006ac0cb44dd0487d18...",2026-10-03 09:30:45
8,27,user-1:puzzles,"{""id"": ""msg_01960a77135184a0006ac0cb45575c87d1...",2026-10-03 09:30:45
9,28,user-1:puzzles,"{""content"": ""map"", ""role"": ""user""}",2026-10-03 09:31:02
10,29,user-1:puzzles,"{""id"": ""rs_01960a77135184a0006ac0cb5742bc87d1a...",2026-10-03 09:31:03
11,30,user-1:puzzles,"{""id"": ""msg_01960a77135184a0006ac0cb5767f087d1...",2026-10-03 09:31:03

In [13]:
display_db_contents(session_id="user-1", task="facts")

History for user-1:facts (9 messages):

,id,session_id,message_data,created_at
0,16,user-1:facts,"{""content"": ""Tell me a fun fact."", ""role"": ""us...",2026-10-03 09:29:22
1,17,user-1:facts,"{""id"": ""rs_0509dea311b866b5006ac0caf42f9487d1b...",2026-10-03 09:29:26
2,18,user-1:facts,"{""id"": ""msg_0509dea311b866b5006ac0caf4bb2887d1...",2026-10-03 09:29:26
3,19,user-1:facts,"{""content"": ""Tell me a fun fact."", ""role"": ""us...",2026-10-03 09:29:44
4,20,user-1:facts,"{""id"": ""rs_0509dea311b866b5006ac0cb0a2cdc87d1a...",2026-10-03 09:29:47
5,21,user-1:facts,"{""id"": ""msg_0509dea311b866b5006ac0cb0abb2c87d1...",2026-10-03 09:29:47
6,22,user-1:facts,"{""content"": ""Tell me a fun fact."", ""role"": ""us...",2026-10-03 09:30:21
7,23,user-1:facts,"{""id"": ""rs_0509dea311b866b5006ac0cb2eed1487d19...",2026-10-03 09:30:23
8,24,user-1:facts,"{""id"": ""msg_0509dea311b866b5006ac0cb2f30bc87d1...",2026-10-03 09:30:23

,id,session_id,message_data,created_at
0,16,user-1:facts,"{""content"": ""Tell me a fun fact."", ""role"": ""us...",2026-10-03 09:29:22
1,17,user-1:facts,"{""id"": ""rs_0509dea311b866b5006ac0caf42f9487d1b...",2026-10-03 09:29:26
2,18,user-1:facts,"{""id"": ""msg_0509dea311b866b5006ac0caf4bb2887d1...",2026-10-03 09:29:26
3,19,user-1:facts,"{""content"": ""Tell me a fun fact."", ""role"": ""us...",2026-10-03 09:29:44
4,20,user-1:facts,"{""id"": ""rs_0509dea311b866b5006ac0cb0a2cdc87d1a...",2026-10-03 09:29:47
5,21,user-1:facts,"{""id"": ""msg_0509dea311b866b5006ac0cb0abb2c87d1...",2026-10-03 09:29:47
6,22,user-1:facts,"{""content"": ""Tell me a fun fact."", ""role"": ""us...",2026-10-03 09:30:21
7,23,user-1:facts,"{""id"": ""rs_0509dea311b866b5006ac0cb2eed1487d19...",2026-10-03 09:30:23
8,24,user-1:facts,"{""id"": ""msg_0509dea311b866b5006ac0cb2f30bc87d1...",2026-10-03 09:30:23

In [5]:
history_json = get_history_json("user-1", "puzzles")
print(history_json)

{
  "session_id": "user-1:puzzles",
  "task": "puzzles",
  "messages": [
    {
      "id": 1,
      "created_at": "2026-10-03 09:26:38",
      "message_data": {
        "content": "Start a new one-word puzzle.",
        "role": "user"
      }
    },
    {
      "id": 2,
      "created_at": "2026-10-03 09:26:42",
      "message_data": {
        "id": "rs_01960a77135184a0006ac0ca50fe2087d1a06acc951261a460",
        "summary": [],
        "type": "reasoning",
        "content": [],
        "encrypted_content": "gAAAAABqwMpSgJiHCzSxWRGSA0JT7rzxl88Lxh0NVobbWXF32kxHanMz1dPcs-4JwJDmij6bjCsig30gZTOvGsh89YIwjdw7CnyaKsgsK4x-wA_gqUSu1LvbR1C6Wxb9lSiF4IfXWa-2xkEUiOkZk8-Xb78eOAS66omym1WaJYmYus8BAJ3-cvvOrIIbwic1yvzc8avNY4IZuNTeAxAtXDW7suHi0PxnBgf9BgFdxEFqyGLyvvEID5Kru22mRMbQqRt4UNePrHJEBerj7M1wmz72VhCxlM88FqEBKkuKxk2ECTIE0CbkjWO3bN2atNtkJd_lvMUDiXjLKGmvA2NC9sOx7D5E_khaLtQKR7CAXVWUV_iFoSKofDAJ8Aymk4I_NiHImCUKFmjnQDcrbgbiSQ-i-bNC06m_xXJxAx2UITqUbtfhqEn-g19yI1LVaQDGEAw3pRfq-zX1cipW7quK6n3M2nRYdI6XgZHvQzoRdHIQKu8duMKppoVDdBscUVAPxVfHK20ZVJ6qlNO3KapM_rQIuapSE1H4o7XmsoGAvd-4flt7BDl0p06tphHcL6CVsqwwM-79R3o_TfRYCyFAci-zKofgtUmL4wwIGGZZBQWUox524R5W6q2kCzgSQyrTue_C6YKzs0IPWoVoLhoasE-PNMBPqVFm_4WYKwQ_FiCz9yAarIHQ4_YMNSsNRXAxe9M7FnXxLE_qA7kVSJDKhyDo1mbROkCbKFrr553PMDMbgGnowWEXoq8QZh4WvGj-csp_DlneDSJVsu50fE7J1NO_R48mLpoePkSDZDxfJTNwbd7wJtMjVJHP5Z8RxsQgj7ZJuUsBbkTWlysKXcQgWUJcqoQfrxN6cOWeG7PWu7sx87b7flejBNQx0DfdWHGnejHBDTsTnp3q7HHMq-fYaZGJiU8oVH0t-sXWjg3YLughosZwSInxSNMjAn2CyeJFlrqyzA6arlKoRQgQZQNYWRPAOHfk6uws7JS9Mi-pxzgaAO9aCPBedKi64_C1wCdEUf1z8XsBdovxOnm3gkX22wba-O2Df9bmG20OkNd1mHwA4TsCgO9v13X8x2PBoCwqp_E7HVp9AvbK5a5D49QOudRl4b3aVyljNoEYW4ekiBlRknx0Zxi4AWOJG56VH8v-W50dF-iJX8RDAUIu6UNv-jckHExxqJvoC529CI-C4U_cLwMhd_gnOr6IUe1IxAi95RzvXLTWhDeo6_kVKrhtJpqYaozvxpRrs2d1nPYUt47EgTHepFiRmDBEeXAyIGBU28Ss_1kAxIdKlLsJlqNBtJqlKFjYb-7NHvVT9JnpbS3jeDf2KdAMzKgeVd1wylLtZLiXc8zJYqHKZDTlGlhrIFFZOh9_N9qrfmdv_tjAU4-6Pj55zAUcHb1OvoyKbju6BNAgMjxsjfAmnUpfE6UQGv1v1Ng_0a21NRAHv9ASZ0bIal2S2EoeGRhE-mU8QYk8BYph3BSKUUUqh3tONbu34GFx7OHj6FkkoA1XidCSZybG8HmoLsek3cuWl4iFYQUg0tEJBl6hPS7Os1ll3XN96Y1_IdfnF_xzfnM3kY4QjTukkNyrYvIBYp5vxP6nYMzrh-Bvrwq2M1TFYr7aZS8L7hC8sOkSuUCyRspq87PZPu_pue8b-B0bRBeF-dMoBVYekt0cNOFtb9I53DKnY4YuUEB-SIUu08WGE1IifqOJArSNP0-dUsomYqo="
      }
    },
    {
      "id": 3,
      "created_at": "2026-10-03 09:26:42",
      "message_data": {
        "id": "msg_01960a77135184a0006ac0ca5213fc87d18ef6a8a72182e0b2",
        "content": [
          {
            "annotations": [],
            "text": "{\"message\":\"I grow shorter as I work, and I can light a room without electricity. What am I? Guess, ask for a hint, or ask for the answer.\",\"status\":\"playing\"}",
            "type": "output_text",
            "logprobs": []
          }
        ],
        "role": "assistant",
        "status": "completed",
        "type": "message",
        "phase": "final_answer"
      }
    },
    {
      "id": 4,
      "created_at": "2026-10-03 09:27:15",
      "message_data": {
        "content": "candle",
        "role": "user"
      }
    },
    {
      "id": 5,
      "created_at": "2026-10-03 09:27:17",
      "message_data": {
        "id": "rs_01960a77135184a0006ac0ca74e70087d19420c321674f6d94",
        "summary": [],
        "type": "reasoning",
        "content": [],
        "encrypted_content": "gAAAAABqwMp1W6RbLt37vcMNe5-lt5e9VeWRXpftpwMId1fiyq43GlL7lU0aBNe2r1ibVK7ZnUMo6KJe5AkMApfDmbzAvgN00s3_NkS3bQAtlAGL5lpDYFQqIXcqKLSeOm8QVYmlNpYo-iyJWx2BeU-A8G49LKBsyih_39l-roeFBSlcG3nt9NjANVVIP6_a--lyzVPInQV-hMeQQ_daty_kGFWfD5-zNj0itVWRVqZIE4XNfX3PwxMWG7PbUQJahya__ac6QfeI8_gg3eO5icS8A9FRTB6Y3UQ_pwreHdwABV1AC9Wj0yfwwNV3jvO-SuBHonWXJhTW0onKHQx3mZV9JcJdgZIxmTL_r4Gb4gEI3_zSHJm7_XeW0dRO5rhHnoUVrvmMrQoEuy6HWzk17zuwvSAC53fo-TCI8Itlen47xFVTjRF8bB6Zd2MadWtGlSFwwJZcA2nfksenyhTRFc-HVxB-MLozrHQOV78KnJjp9cD7rTfLwlpHLrUyD5EYXQUh4cngYqpfxxpGERd0FUrIyqcIijAkD8Be8NGtKrI1lfhFjxCGRPAixwRZpa771MUpeAeupAQ1_8Q2GEI1tCReq1HkRmGi9vgJOPcCOdnPX97uw-dJmevgwoI5PGe4Gdab1olSzoNYirndOn0YrfMyYfjLdOzxALwP1wrw6cmon9T0UM0aK1LI0IeSi04kzNu4ZplYfWHjOdfjS77oovuPUT9v_oc9IxrudJuXbI7Fn2wzx7KtaUyTlF2w3A8CkOxiwCqu2Gx7PTer2nLahCJm57huDnqjYuO_RndjtPmWeggAcVjm628_oz-6AlLqpzojFoo4nClPwt4WzBjkJg6xywOocL6U_VGrQv9Pt9-xRi0BBrhKxYK2maLsKzXP58XiJOwezlxMMWordVP7xUUMcqK5WRSJCF6hvQVcz34XkcXN6CFfmcQ94sPxfCslKti1I-jJ8v-K9fpLmpSuSq01zdfPnvKx8NUiDTTSK44UHltoXq8hk5ULC8lE37b432hCk6msdyigWlt_wBxqjnFHNEUmIUPW9MacYmXw7Qf9qyp01Zxwr_Ae9jlKqEkp7VatY_Rc1YAYEn8ylS4At-hMl2hL8mNzZtvN4Tl5PgNfud_maJ2mdZc2djRdSKmol1siiBJMMgINfnE-D-SljuV_MyrVRgvfJx0oybk1Cnwg5HWla_DHMDU6Tz0XUAtcVHLjagDgBJ0fUqFObW5F7LO4NoCD0GHqxwtHov9u_F3ZnMR1swhfn2w="
      }
    },
    {
      "id": 6,
      "created_at": "2026-10-03 09:27:17",
      "message_data": {
        "id": "msg_01960a77135184a0006ac0ca75194887d18cfdfcedd442cc90",
        "content": [
          {
            "annotations": [],
            "text": "{\"message\":\"That’s right! The answer is **candle**: it gives light as it burns down and grows shorter.\",\"status\":\"solved\"}",
            "type": "output_text",
            "logprobs": []
          }
        ],
        "role": "assistant",
        "status": "completed",
        "type": "message",
        "phase": "final_answer"
      }
    },
    {
      "id": 25,
      "created_at": "2026-10-03 09:30:43",
      "message_data": {
        "content": "Start a new one-word puzzle.",
        "role": "user"
      }
    },
    {
      "id": 26,
      "created_at": "2026-10-03 09:30:45",
      "message_data": {
        "id": "rs_01960a77135184a0006ac0cb44dd0487d18788400dd577cfa6",
        "summary": [],
        "type": "reasoning",
        "content": [],
        "encrypted_content": "gAAAAABqwMtGsqbBw1Z7aF0o6k3MqXFM0RZsGI71BAY0n_ej2HLsTXk1HPmoijgZNNOrmXsZd2ujYoiyKbrtCqPYaJGgF-3h0eU3HETrdfLik50A_-isjlwIo3Va6P4ox6pPlyso5dgPDXma9lwOb1VjWYLjV5QmWR5XZfZUy_m4Se1JpeKh_sKIhaDBuqqyhhQEvGtPup9HGMFj3yiaILEutU75vPFCO5ICH07mtGRfPpBpgjPa8QaRNssKILrRmsP_QzCaEmpZVCui7_0LOGtONTmR9FCNtbVV8IgebkGV5Iz080RUW6nPBtUNC0vnLAY_x3mxAUz4J_mMWkk66mqPwWx5HC-0S0uR9JsMv_GYiF3ya3DFTJBzAKP9RVl44ZApSg3fOjs5_rXr73DfnoMIs1C1HFz8SFVgXGjGQBY3i-xb6_BfbGcey7obP2BEE8j7ryhYtMnYFhfnv3aK5JiEQzIgRGKOZCqkHy6U0ZKVucBnlAaBK6gPpwfuNFmSnV1Bmn65bqE4amhmXSr6hl2ZeY3g9S4JUDvXiiBm-w1q1w42BRuk3rtXZlv44_OaR8MKM7mT1e5WH54s_AmW6C425C4zMc_KmQjhpSELwugmSpfOw3jcxEJjZQx-PG3SV5ypbsK-Ua4tWWPyMvM617idsEy8JQj9UXl4LJCIbHBZyP8QC2SAiZGqUUm9pVrLVOj1VWySvzomvpgxZla4WRWD9eTwhJte38lovasWW5Yb-LC5mY06JSoo-NuZNmbyhg12lzhj2BO8px08QH4ZbFUfGyHUofuTgJUyy7Y-6VKsK1JAiUo5xeWqDo1pqNBnf2i00B0QretWV54ZabM7r-Q2fiEkupO_xICN9upWf8Vorm2MI6yF0oTWTzBOxbvZA2tZwhBPsXFo-w4-88qzPDwHZtV_dItS213qyr7IqA5t1v8D-zWMRyPiq21OHC9rb8Vtidv6EryWqDp6Qv5nFQ6PrkNzPrHt7VKzuB8eQ4lhereHS7oC-NFP4kPXMJWn-CDGQnCjcReaO15Yehsm1ABzpRel6pNCTq_7HlVBt4Xz_9hjYg3ZJ7f9PuTOpSK9W3RDc7NeIFmeaI0BUfiuD__4ANgyj_2K5wNmWc1YGSwNMc4BhcArf6m1RKgQxflnXr4iEAw0QTrwY2XTxDecYk29_rqRG2vJyz986-rFKqvwDy5pxcLhCdb7cSpMzDnKLjPv9GVGl9cqeqkxDMP-4IqLVWO_Q7nlEWr65pByJqBEyDPLhtsNcRM_m-e_1Q21M6mg-CSiEM_FIemWmp2_za-dvlHCsht12rj1moMNmXPYIWNe7flF4rriw_HyYgl3xZc58xh5_eTezI-A44xhVzktuFP5BtbBR1wCjepio_HE4yyY2Y8so1tFb_XZ9gjkjhtq27Eb02ItqAJX2NO4VlKCqdqk4iKiHKuzzgy3Ug1d-CmXlkYpt_VkIKKKzywY2cyzuDS7opYWH39QAgF5xCZUizPvzHr0ps__2jGCHYoQ-5mkRmzt3Ys="
      }
    },
    {
      "id": 27,
      "created_at": "2026-10-03 09:30:45",
      "message_data": {
        "id": "msg_01960a77135184a0006ac0cb45575c87d1829f4da29854bc06",
        "content": [
          {
            "annotations": [],
            "text": "{\"message\":\"I show roads, rivers, and mountains, but contain no actual land or water. What am I? Guess, ask for a hint, or ask for the answer.\",\"status\":\"playing\"}",
            "type": "output_text",
            "logprobs": []
          }
        ],
        "role": "assistant",
        "status": "completed",
        "type": "message",
        "phase": "final_answer"
      }
    },
    {
      "id": 28,
      "created_at": "2026-10-03 09:31:02",
      "message_data": {
        "content": "map",
        "role": "user"
      }
    },
    {
      "id": 29,
      "created_at": "2026-10-03 09:31:03",
      "message_data": {
        "id": "rs_01960a77135184a0006ac0cb5742bc87d1aaa0370242bc1cf9",
        "summary": [],
        "type": "reasoning",
        "content": [],
        "encrypted_content": "gAAAAABqwMtXOui2Lc148ezwwKeTOANBvWBqg6z2maNH1kCyNwIRS2s46lpZs_deayjcLLacmaeKc8xFa5BbNlSWfo47eLNK8F-mCB5K5J8PbOV_GYj00AyjtPhC6G3w4_PZieH3EjkL1F4joMI1ySTLRrq8OM06lemhH5jRs152eRhstrUrEsVKrFsT0PYU3_gcR1V6UjNz8dygGfBkgPSLNmWNBlUHsk0tUpE3Zu7iHx6MI3b-Rt6yrIV9jP5PMMtFz-PZbnSr3k02maf4tgAhOo8kYw-1YxMC5sOzBSQzKJ8ZUBwUfLP537P4dLcs8d3R2jM3EPMoyPW3hBdp34-EAh1X6AoUchYVX_qMS7ZY-msWLqGbISvBuIoW5v6bxG4xPnTeGm22VWsX7GEtk653inZKPzsSNIKfRRV8sEezWJZm11Vlk52sdrN45Xj73zVmIXHq45Fe9mnLe5DmnyVKFfHnGHC7Bm3PBAcxcHHO9MZfGEkousMHBTRwyaupReFW9D8Ak_gWSzFj7VJtdV9ZKYhbnV0wo836--9umD9TX3XwZueMporV_dcTuEcUihCaL96rb3JVog5P3rL13YBzKOa3UZAOBOnK3JRtX0No0HtEjKuoVEJjVDXVdrlW88f6BnrSj6bGAgTUnTZc3_xNagztzRYTSlKVw5qJlGksGC2zC1yf9RzPG4lYKN405vpxdJBKZRemUWNuaqIZtV_PqkclFBTtjZgRvPwuCIJYzCfafUUJiLpqx0E2GGBGai33REg6mFUn7YgbB7X_LBB5L2G8_qpUFn7SwwQPD5GEZRqoLVqkCb4RMftg4c3vxA7YM4RM5E39UNMmwDEPK6utaZ9zJpAV_LcVolDsbrwob8ln_mdJxjkS9Txw0tGP-J5L8shIDc-dIbkjFbYhNSOqDBEo6nmmx_qMpvzHp-cKvdDdZBikKrrrYLGINhfo84schGXv0EdtdlfYzHpJkItpjf64HfeZltdSPfEVrfnaHl6dl11UEvl5ZfgYxC9aTIZS-7C1veOZ6WxM0llHjNgPswEoVQMYMVtXvB1zRrbXnv64S1XMJ-3NDcdrUtV-SPujesda-ntll84tZha6kt4DJhp7g5a5Vbckvdydjj6n75wpkPiQE0h7vovj95NWytAWtY-yY83aWB5Mhbi5MRMhKOzgHj89IBLpGLaSlf8gRqSAvZa__N8="
      }
    },
    {
      "id": 30,
      "created_at": "2026-10-03 09:31:03",
      "message_data": {
        "id": "msg_01960a77135184a0006ac0cb5767f087d1ac2796c29ec12a96",
        "content": [
          {
            "annotations": [],
            "text": "{\"message\":\"Correct! The answer is **map**: it represents roads, rivers, and mountains without containing the real things.\",\"status\":\"solved\"}",
            "type": "output_text",
            "logprobs": []
          }
        ],
        "role": "assistant",
        "status": "completed",
        "type": "message",
        "phase": "final_answer"
      }
    }
  ]
}

In [7]:
tables = get_db_tables()
tables

{'agent_sessions':        session_id           created_at           updated_at
 0    user-1:facts  2026-10-03 09:29:22  2026-10-03 09:30:23
 1    user-1:jokes  2026-10-03 09:28:40  2026-10-03 09:29:12
 2  user-1:puzzles  2026-10-03 09:26:38  2026-10-03 09:31:03,
 'agent_messages':     id      session_id                                       message_data  \
 0    1  user-1:puzzles  {"content": "Start a new one-word puzzle.", "r...
 1    2  user-1:puzzles  {"id": "rs_01960a77135184a0006ac0ca50fe2087d1a...
 2    3  user-1:puzzles  {"id": "msg_01960a77135184a0006ac0ca5213fc87d1...
 3    4  user-1:puzzles              {"content": "candle", "role": "user"}
 4    5  user-1:puzzles  {"id": "rs_01960a77135184a0006ac0ca74e70087d19...
 5    6  user-1:puzzles  {"id": "msg_01960a77135184a0006ac0ca75194887d1...
 6    7    user-1:jokes     {"content": "Tell me a joke.", "role": "user"}
 7    8    user-1:jokes  {"id": "rs_09fe2fd1198667a0006ac0cac9930887d1a...
 8    9    user-1:jokes  {"id": "msg_09fe2fd1198667a0006ac0caca15a487d1...
 9   10    user-1:jokes     {"content": "Tell me a joke.", "role": "user"}
 10  11    user-1:jokes  {"id": "rs_09fe2fd1198667a0006ac0cad7140c87d1b...
 11  12    user-1:jokes  {"id": "msg_09fe2fd1198667a0006ac0cad7364887d1...
 12  13    user-1:jokes     {"content": "Tell me a joke.", "role": "user"}
 13  14    user-1:jokes  {"id": "rs_09fe2fd1198667a0006ac0cae7236c87d19...
 14  15    user-1:jokes  {"id": "msg_09fe2fd1198667a0006ac0cae84b2487d1...
 15  16    user-1:facts  {"content": "Tell me a fun fact.", "role": "us...
 16  17    user-1:facts  {"id": "rs_0509dea311b866b5006ac0caf42f9487d1b...
 17  18    user-1:facts  {"id": "msg_0509dea311b866b5006ac0caf4bb2887d1...
 18  19    user-1:facts  {"content": "Tell me a fun fact.", "role": "us...
 19  20    user-1:facts  {"id": "rs_0509dea311b866b5006ac0cb0a2cdc87d1a...
 20  21    user-1:facts  {"id": "msg_0509dea311b866b5006ac0cb0abb2c87d1...
 21  22    user-1:facts  {"content": "Tell me a fun fact.", "role": "us...
 22  23    user-1:facts  {"id": "rs_0509dea311b866b5006ac0cb2eed1487d19...
 23  24    user-1:facts  {"id": "msg_0509dea311b866b5006ac0cb2f30bc87d1...
 24  25  user-1:puzzles  {"content": "Start a new one-word puzzle.", "r...
 25  26  user-1:puzzles  {"id": "rs_01960a77135184a0006ac0cb44dd0487d18...
 26  27  user-1:puzzles  {"id": "msg_01960a77135184a0006ac0cb45575c87d1...
 27  28  user-1:puzzles                 {"content": "map", "role": "user"}
 28  29  user-1:puzzles  {"id": "rs_01960a77135184a0006ac0cb5742bc87d1a...
 29  30  user-1:puzzles  {"id": "msg_01960a77135184a0006ac0cb5767f087d1...

              created_at
 0   2026-10-03 09:26:38
 1   2026-10-03 09:26:42
 2   2026-10-03 09:26:42
 3   2026-10-03 09:27:15
 4   2026-10-03 09:27:17
 5   2026-10-03 09:27:17
 6   2026-10-03 09:28:40
 7   2026-10-03 09:28:42
 8   2026-10-03 09:28:42
 9   2026-10-03 09:28:53
 10  2026-10-03 09:28:55
 11  2026-10-03 09:28:55
 12  2026-10-03 09:29:10
 13  2026-10-03 09:29:12
 14  2026-10-03 09:29:12
 15  2026-10-03 09:29:22
 16  2026-10-03 09:29:26
 17  2026-10-03 09:29:26
 18  2026-10-03 09:29:44
 19  2026-10-03 09:29:47
 20  2026-10-03 09:29:47
 21  2026-10-03 09:30:21
 22  2026-10-03 09:30:23
 23  2026-10-03 09:30:23
 24  2026-10-03 09:30:43
 25  2026-10-03 09:30:45
 26  2026-10-03 09:30:45
 27  2026-10-03 09:31:02
 28  2026-10-03 09:31:03
 29  2026-10-03 09:31:03  }